tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "mongodb/brew"
brew "gh"
brew "htop"
brew "lua-language-server"
brew "neovim"
brew "node", link: false
brew "ripgrep"
brew "stylua"
brew "wget"
brew "yarn"
